include: package:very_good_analysis/analysis_options.yaml

analyzer:
errors:
  invalid_annotation_target: ignore
linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    constant_identifier_names: false
    sort_pub_dependencies: false
    cascade_invocations: false
    sort_constructors_first: false